export const ROUTES = {
  // public
  landing: '/',
  // auth
  login: '/auth/login',
  register: '/auth/register',
  forgot: '/auth/forgot-password',
  reset: '/auth/reset-password',
  mfa: '/auth/mfa',
  verify: '/auth/verify-email',
  // app
  dashboard: '/dashboard',
  accounts: '/accounts',
  newAccount: '/accounts/new',
  account: (id = ':accountId') => `/accounts/${id}`,
  accountStatement: (id = ':accountId') => `/accounts/${id}/statement`,
  transactions: '/transactions',
  transaction: (id = ':txId') => `/transactions/${id}`,
  transfer: '/transactions/transfer',
  scheduledTransfers: '/transactions/scheduled',
  cards: '/cards',
  issueCard: '/cards/issue',
  card: (id = ':cardId') => `/cards/${id}`,
  cardTransactions: (id = ':cardId') => `/cards/${id}/transactions`,
  payments: '/payments',
  checkout: '/payments/checkout',
  payBills: '/payments/pay-bills',
  merchants: '/payments/merchants',
  loans: '/loans',
  applyLoan: '/loans/apply',
  loan: (id = ':loanId') => `/loans/${id}`,
  mortgages: '/mortgages',
  applyMortgage: '/mortgages/apply',
  mortgage: (id = ':mortgageId') => `/mortgages/${id}`,
  savings: '/savings',
  applySavings: '/savings/apply',
  investments: '/investments',
  investmentAssets: '/investments/assets',
  investmentAsset: (s = ':symbol') => `/investments/assets/${s}`,
  portfolio: (id = ':accountId') => `/investments/${id}/portfolio`,
  fx: '/fx',
  beneficiaries: '/beneficiaries',
  notifications: '/notifications',
  notification: (id = ':id') => `/notifications/${id}`,
  profile: '/profile',
  security: '/profile/security',
  preferences: '/profile/preferences',
  // admin/employee
  admin: '/admin',
  adminUsers: '/admin/users',
  adminUser: (id = ':id') => `/admin/users/${id}`,
  adminRoles: '/admin/roles',
  audit: '/admin/audit',
  templates: '/admin/notifications/templates',
  workflow: '/workflow',
  workflowDetail: (id = ':id') => `/workflow/${id}`,
  // system
  forbidden: '/forbidden',
};

