name: aether-bank-backend

services:
  # 1) PostgreSQL (IAM + Transaction Service)
  postgres:
    image: postgres:15-alpine
    container_name: bank-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transaction_service
    ports:
      - "5433:5432"   # host:container
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  # 2) MySQL (Account + Card Service)
  mysql:
    image: mysql:8.0
    container_name: bank-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: account_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  # 3) MongoDB (Lending + Notification Service)
  mongodb:
    image: mongo:6.0
    container_name: bank-mongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    
  
  mongo-express:
    image: mongo-express
    container_name: bank-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/ # Uses the internal Docker network
    depends_on:
      - mongodb
  
  # 4) RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: bank-rabbitmq
    restart: always
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  mysql_data:
  mongodb_data:
  rabbitmq_data:
 
