server:
  port: 8080

spring:
  application:
    name: financial-service

  devtools:
    restart:
      enabled: true
      additional-paths:
        - src/main/java
        - src/main/resources
      exclude:
        - static/**
        - public/**
    livereload:
      enabled: true

  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    uri: ${SPRING_MONGODB_URI:${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/financial_service}}
    representation:
      uuid: standard

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5673}
    publisher-confirm-type: correlated
    publisher-returns: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
