server:
  port: 8080

spring:
  application:
    name: financial-service

  devtools:
    restart:
      enabled: true
      additional-paths:
        - src/main/java
        - src/main/resources
      exclude:
        - static/**
        - public/**
    livereload:
      enabled: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/financial_service
      uuid-representation: standard
      auto-index-creation: true

  rabbitmq:
    host: localhost
    port: 5673
    publisher-confirm-type: correlated
    publisher-returns: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
