server:
  port: 9000 # The single port your frontend will talk to

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Let gateway use Eureka to find services
      routes:
        - id: transaction-service-route
          uri: lb://transaction-service # lb = Load Balancer. It asks Eureka for the IP!
          predicates:
            - Path=/api/transactions/** # If a request starts with this, send it to the transaction service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/