server:
  port: 8084

spring:
  application:
    name: card-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/card_db
    username: postgres
    password: mahi234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

veld:
  sdk:
    transaction:
      base-url: http://localhost:2501

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
